# This file was generated by GoReleaser. DO NOT EDIT.
class ReadOotsCli < Formula
  desc "Keep up on OotS comics and never leave the terminal window."
  homepage "https://github.com/Maahsome/read-oots-cli"
  version "0.0.6"
  license "MIT"

  if OS.mac?
    url "https://github.com/maahsome/read-oots-cli/releases/download/v0.0.6/read-oots-cli_0.0.6_Darwin_x86_64.tar.gz"
    sha256 "615cd91f01a2de5ce4fb80b00d5e40bdc86676a17e944fd72c62e1f5a5f3467b"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/maahsome/read-oots-cli/releases/download/v0.0.6/read-oots-cli_0.0.6_Linux_x86_64.tar.gz"
    sha256 "7f871e0c810144c8be74bdea507ad8d8035d304bd055efa6428f7e4c4e9e8bcf"
  end

  depends_on "mdcat"

  def install
    bin.install "read-oots-cli"
  end

  test do
    system "#{bin}/read-oots-cli version"
  end
end
